name: ${project.name}
main: net.azisaba.soundabsorber.SoundAbsorber
version: ${project.version}
author: siloneco
depend: [ProtocolLib]
description: ${project.description}
website: ${project.url}
commands:
  soundabsorber:
    aliases: ["sa"]
    permission: soundabsorber.command.soundabsorber
    usage: /soundabsorber
permissions:
  soundabsorber.command.soundabsorber:
    default: true